[package]
name = "javav-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
classfile-parser = "0.3.7"
zip = "0.6.6"
anyhow = "1.0.72"
